[TABLE="class: cms_table_cms_table_cms_table_cms_table_cms_table_cms_table, width: 900, align: center"]
[TR="bgcolor: #999900"]
[TD="align: center"]%question%[/TD]
[/TR]
[TR]
[TD="align: center"]%answer%[/TD]
[/TR]
[/TABLE]