import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "public/MainStyle.css";
import Head from "next/head";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "מחולל צוות פיד החדש!",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="he" dir="rtl">
      <Head>
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&display=swap&subset=hebrew" rel="stylesheet" />
        <style>{`body { font-family: 'Open Sans', 'Open Sans Hebrew', Arial, sans-serif !important; }`}</style>
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col bg-black`}
      >
        <div className="flex-1 w-full flex flex-col">
          {children}
        </div>
        <footer className="w-full text-center py-6 bg-gray-800 text-gray-300 text-lg mt-auto">
          קרדיט:
          <a href="https://www.fxp.co.il/member.php?u=159073" target="_blank" rel="noopener noreferrer" className="text-blue-400 hover:underline mx-2">RemixN1V</a>
          &amp;
          <a href="https://www.fxp.co.il/member.php?u=1013527" target="_blank" rel="noopener noreferrer" className="text-blue-400 hover:underline mx-2">ModerniMan</a>
        </footer>
      </body>
    </html>
  );
}
