import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "public/MainStyle.css";

import Header from "./Header";
import credits from './panel/admin/credits.json';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "מחולל צוות פיד החדש!",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="he" dir="rtl">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <Header />
        <div className="flex-1 w-full flex flex-col">
          {children}
        </div>
        <footer className="w-full text-center py-6 bg-gray-800 text-gray-300 text-lg mt-auto">
          קרדיט:
          {credits && credits.length > 0 && credits.map((c, i) => (
            <span key={i}>
              <a
                href={c.profile}
                target="_blank"
                rel="noopener noreferrer"
                className="text-blue-400 hover:underline mx-2"
              >
                {c.nick}
              </a>
              {i < credits.length - 1 && <span>&amp;</span>}
            </span>
          ))}
        </footer>
      </body>
    </html>
  );
}
